accelerate launch --mixed_precision=bf16 src/train_difix_guava.py \
    --report_to=wandb \
    --tracker_project_name=difix \
    --tracker_run_name=train_v0.1.0-mix \
    --seed=42 \
    --output_dir=outputs/difix/train \
    --dataset_path=/home/szj/err_empty_syn/ytb/bbox_square_x1.1/outputs/render_for_difix_v0.1.0/difix_data.json \
    --max_train_steps=15010 \
    --num_training_epochs=1 \
    --resolution=512 \
    --learning_rate=2e-5 \
    --lr_scheduler="cosine" \
    --train_batch_size=1 \
    --dataloader_num_workers=8 \
    --enable_xformers_memory_efficient_attention \
    --checkpointing_steps=5000 \
    --eval_freq=-1 \
    --viz_freq=100 \
    --lambda_lpips=1.0 \
    --lambda_l2=1.0 \
    --lambda_gram=1.0 \
    --gram_loss_warmup_steps=2000 \
    --timestep=199 \
    --mv_unet

